kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: s2i-custom-notebook
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 's2i-custom-notebook:jupyter'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'notebook image repository URL'
    contextDir: /container-images/s2i-custom-notebook
    sourceSecret:
      name: gitlab-access
  runPolicy: Serial
